import { useRef, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { saveHistoryEntry } from "@/lib/history-store";
import { toast } from "sonner";

const STACKS = [
  "Full-Stack Mobile",
  "Node.js + PostgreSQL",
  "Python FastAPI",
  "Next.js Serverless",
];

const TABS = [
  { id: "architecture", label: "System Architecture" },
  { id: "schema", label: "Database Schema" },
  { id: "readme", label: "Production README" },
  { id: "prompt", label: "AI Workflow Prompt" },
] as const;

type TabId = (typeof TABS)[number]["id"];

const STATIC_ARCH = `┌──────────────┐      ┌──────────────┐      ┌──────────────┐
│   Client     │─────▶│   API Layer  │─────▶│   Services   │
│  (Mobile/Web)│◀─────│  (REST/GRPC) │◀─────│  (Business)  │
└──────────────┘      └──────┬───────┘      └──────┬───────┘
                             │                     │
                             ▼                     ▼
                      ┌──────────────┐      ┌──────────────┐
                      │  Auth / JWT  │      │  PostgreSQL  │
                      └──────────────┘      └──────────────┘
                             │                     │
                             ▼                     ▼
                      ┌──────────────┐      ┌──────────────┐
                      │  Redis Cache │      │  Object Store│
                      └──────────────┘      └──────────────┘`;

const STATIC_SCHEMA = `-- users
CREATE TABLE users (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email       TEXT UNIQUE NOT NULL,
  display_nm  TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_users_email ON users(email);

-- sessions
CREATE TABLE sessions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID REFERENCES users(id) ON DELETE CASCADE,
  token_hash  TEXT NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL
);

-- quizzes
CREATE TABLE quizzes (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id    UUID REFERENCES users(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  payload     JSONB NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_quizzes_owner ON quizzes(owner_id);`;

const STATIC_README = `# System Architecture

A production-grade application generated by MS Arch.

## Stack
- Client: React / React Native (TypeScript)
- API:    Node.js · Fastify · Zod
- Data:   PostgreSQL 16 (RLS) · Redis · S3-compatible object storage

## Getting Started
\`\`\`bash
pnpm install
pnpm db:migrate
pnpm dev
\`\`\`

## Deployment
- Containerized via Docker, orchestrated on Kubernetes
- CI/CD: GitHub Actions -> staging -> production
- Observability: OpenTelemetry -> Grafana + Loki
`;

function buildMasterPrompt(concept: string, stack: string) {
  const idea = concept.trim() || "[describe your application concept here]";
  return `You are a senior systems architect. Generate a complete, step-by-step build plan for the following application.

APP CONCEPT:
${idea}

TARGET STACK: ${stack}

Deliver the response in the following exact sections, in order:

1. LOGIC WORKFLOW
   - Enumerate the end-to-end user journeys.
   - For each journey, list the discrete steps, decision points, and system actors.
   - Identify async jobs, background workers, and event triggers.

2. DATA HANDLING STRUCTURE
   - Define all entities, relationships, and cardinalities.
   - Provide normalized SQL schema (tables, columns, types, indexes, foreign keys).
   - Specify validation rules and access boundaries (row-level security).

3. APPLICATION SCREEN MAP
   - List every screen / route with its purpose.
   - For each screen: required data, primary actions, navigation targets, empty/loading/error states.
   - Indicate auth requirements per screen.

4. API CONTRACT
   - REST or RPC endpoints grouped by domain.
   - For each: method, path, auth scope, request shape, response shape, status codes.

5. IMPLEMENTATION ORDER
   - A numbered, dependency-aware checklist a developer can execute top-to-bottom.

Constraints:
- Be exhaustive and unambiguous; no placeholders.
- Use plain markdown.
- Do not ask clarifying questions; make reasonable assumptions and state them at the top.`;
}

type AgentStatus = "idle" | "running" | "done" | "error";
type Phase = "idle" | "thinking" | "ready";

const AGENT_LABELS: Record<TabId, string> = {
  architecture: "Architecture Agent",
  schema: "Schema Agent",
  readme: "Docs Agent",
  prompt: "Prompt Agent",
};

const INITIAL_STATUS: Record<TabId, AgentStatus> = {
  architecture: "idle",
  schema: "idle",
  readme: "idle",
  prompt: "idle",
};

async function callRunAgent(input: {
  agentId: TabId;
  concept: string;
  stack: string;
  deepThink: boolean;
}): Promise<{ agentId: TabId; text: string; error: boolean }> {
  const res = await fetch("/api/run-agent", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
  });
  const body = await res.json().catch(() => null);
  if (!res.ok) {
    // If our API returned a structured error with a text field, surface it
    if (body && typeof (body as { text?: string }).text === "string") {
      return {
        agentId: input.agentId,
        text: (body as { text: string }).text,
        error: true,
      };
    }
    const msg =
      typeof (body as { error?: string })?.error === "string"
        ? (body as { error: string }).error
        : `HTTP ${res.status}`;
    throw new Error(msg);
  }
  return body as { agentId: TabId; text: string; error: boolean };
}

export function WorkspacePage() {
  const [tab, setTab] = useState<TabId>("architecture");
  const [stack, setStack] = useState(STACKS[0]);
  const [prompt, setPrompt] = useState("");
  const [deepThink, setDeepThink] = useState(false);
  const [statuses, setStatuses] =
    useState<Record<TabId, AgentStatus>>(INITIAL_STATUS);
  const [results, setResults] = useState<Partial<Record<TabId, string>>>({});
  const abortRef = useRef<{ cancelled: boolean } | null>(null);

  const anyRunning = TABS.some((t) => statuses[t.id] === "running");
  const allDone = TABS.every(
    (t) => statuses[t.id] === "done" || statuses[t.id] === "error",
  );
  const phase: Phase = anyRunning ? "thinking" : allDone ? "ready" : "idle";

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      toast.error("Describe your application concept first.");
      return;
    }
    const token = { cancelled: false };
    abortRef.current = token;
    setResults({});
    setStatuses({
      architecture: "running",
      schema: "running",
      readme: "running",
      prompt: "running",
    });

    const collected: Partial<Record<TabId, string>> = {};

    await Promise.all(
      TABS.map(async (t) => {
        try {
          const res = await callRunAgent({
            agentId: t.id,
            concept: prompt,
            stack,
            deepThink,
          });
          if (token.cancelled) return;
          collected[t.id] = res.text;
          setResults((prev) => ({ ...prev, [t.id]: res.text }));
          setStatuses((prev) => ({
            ...prev,
            [t.id]: res.error ? "error" : "done",
          }));
        } catch (err) {
          if (token.cancelled) return;
          setStatuses((prev) => ({ ...prev, [t.id]: "error" }));
          setResults((prev) => ({
            ...prev,
            [t.id]: `> ⚠️ This section could not be generated. Please try again.`,
          }));
          console.error(err);
        }
      }),
    );

    if (token.cancelled) return;

    const full = {
      architecture: collected.architecture ?? "",
      schema: collected.schema ?? "",
      readme: collected.readme ?? "",
      prompt: collected.prompt ?? "",
    };
    if (Object.values(full).every((v) => v.length > 0)) {
      saveHistoryEntry({
        concept: prompt,
        stack,
        mode: deepThink ? "deep" : "fast",
        results: full,
      });
    }
  };

  const handleCancel = () => {
    if (abortRef.current) abortRef.current.cancelled = true;
    setStatuses(INITIAL_STATUS);
    setResults({});
  };

  const masterPrompt = buildMasterPrompt(prompt, stack);

  const fallback: Record<TabId, string> = {
    architecture: STATIC_ARCH,
    schema: STATIC_SCHEMA,
    readme: STATIC_README,
    prompt: masterPrompt,
  };

  const currentStatus = statuses[tab];
  const currentContent = results[tab] ?? (phase === "idle" ? fallback[tab] : "");

  return (
    <AppShell>
      <div className="page-transition flex flex-col lg:flex-row lg:h-screen lg:overflow-hidden w-full max-w-full">
        <section className="w-full lg:w-2/5 lg:max-w-[480px] lg:border-r border-b lg:border-b-0 border-border bg-surface flex flex-col lg:h-screen lg:overflow-y-auto shrink-0">
          <div className="px-5 md:px-8 py-6 border-b border-border">
            <div className="text-[11px] uppercase tracking-[0.22em] text-muted-foreground">
              Control Panel
            </div>
            <h1 className="mt-1 text-2xl font-semibold tracking-tight">
              System Architect
            </h1>
            <p className="mt-1 text-sm text-muted-foreground">
              Describe your idea. We design the system.
            </p>
          </div>

          <div className="px-5 md:px-8 py-6 space-y-5">
            <div className="space-y-2">
              <label className="text-[11px] font-medium text-muted-foreground uppercase tracking-[0.18em]">
                Application concept
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Describe your application concept in plain English..."
                className="block w-full min-h-[140px] resize-y bg-input border border-border px-4 py-3 text-sm leading-relaxed placeholder:text-muted-foreground/70 focus:outline-none focus:border-foreground transition"
              />
            </div>

            <div className="space-y-2">
              <label className="text-[11px] font-medium text-muted-foreground uppercase tracking-[0.18em]">
                Tech stack
              </label>
              <select
                value={stack}
                onChange={(e) => setStack(e.target.value)}
                className="block w-full bg-input border border-border px-4 py-3 text-sm focus:outline-none focus:border-foreground transition"
              >
                {STACKS.map((s) => (
                  <option key={s} value={s}>
                    {s}
                  </option>
                ))}
              </select>
            </div>

            <button
              type="button"
              onClick={() => setDeepThink((v) => !v)}
              aria-pressed={deepThink}
              className={`w-full flex items-center justify-between gap-3 border px-4 py-3 text-left transition ${
                deepThink
                  ? "border-foreground bg-surface-elevated"
                  : "border-border bg-input hover:border-foreground/60"
              }`}
            >
              <div className="min-w-0">
                <div className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
                  Complex Thinking
                </div>
                <div className="text-sm mt-0.5">
                  {deepThink
                    ? "Deep mode · slower, more thorough"
                    : "Fast mode · quick draft"}
                </div>
              </div>
              <span
                className={`shrink-0 h-5 w-9 border border-border relative transition ${
                  deepThink ? "bg-foreground" : "bg-surface"
                }`}
              >
                <span
                  className={`absolute top-0.5 h-3.5 w-3.5 transition-all ${
                    deepThink
                      ? "left-[18px] bg-background"
                      : "left-0.5 bg-foreground"
                  }`}
                />
              </span>
            </button>

            <div className="flex flex-col sm:flex-row gap-2">
              <button
                type="button"
                onClick={handleGenerate}
                disabled={phase === "thinking"}
                className="flex-1 bg-accent text-accent-foreground font-medium text-sm py-3 transition hover:opacity-90 active:opacity-80 disabled:opacity-60"
              >
                {phase === "thinking"
                  ? "Agents Working..."
                  : "Generate System Architecture"}
              </button>
              {phase === "thinking" && (
                <button
                  type="button"
                  onClick={handleCancel}
                  className="sm:w-32 border border-border bg-surface text-foreground font-medium text-sm py-3 transition hover:bg-surface-elevated"
                >
                  Cancel
                </button>
              )}
            </div>

            <AgentStatusList statuses={statuses} phase={phase} />

            <p className="pt-2 text-[11px] text-muted-foreground border-t border-border">
              Output streams into the four tabs as each agent finishes.
            </p>
          </div>
        </section>

        <section className="w-full lg:flex-1 min-w-0 flex flex-col bg-background lg:h-screen lg:overflow-hidden">
          <div className="shrink-0 border-b border-border w-full max-w-full overflow-x-auto">
            <div className="flex items-stretch min-w-0">
              {TABS.map((t) => {
                const active = t.id === tab;
                const s = statuses[t.id];
                return (
                  <button
                    key={t.id}
                    onClick={() => setTab(t.id)}
                    className={`whitespace-nowrap px-3 md:px-4 py-3 text-[11px] md:text-[12px] uppercase tracking-[0.12em] md:tracking-[0.14em] border-r border-border transition-colors flex-1 min-w-0 flex items-center justify-center gap-2 ${
                      active
                        ? "bg-surface text-foreground border-b-2 border-b-foreground -mb-px"
                        : "text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    <span className="block truncate">{t.label}</span>
                    <StatusDot status={s} />
                  </button>
                );
              })}
            </div>
          </div>

          <div className="flex-1 min-h-0 overflow-y-auto p-4 md:p-6">
            {phase === "idle" && Object.keys(results).length === 0 ? (
              <EmptyState />
            ) : currentStatus === "running" ? (
              <AgentRunningPanel label={AGENT_LABELS[tab]} />
            ) : currentContent ? (
              <OutputPanel tab={tab} content={currentContent} status={currentStatus} />
            ) : (
              <AgentRunningPanel label={AGENT_LABELS[tab]} />
            )}
          </div>
        </section>
      </div>
    </AppShell>
  );
}

function Spinner({ className = "" }: { className?: string }) {
  return (
    <span
      className={`inline-block h-3 w-3 rounded-full border-2 border-muted-foreground/30 border-t-foreground animate-spin ${className}`}
      aria-hidden
    />
  );
}

function StatusDot({ status }: { status: AgentStatus }) {
  if (status === "running") return <Spinner />;
  if (status === "done")
    return (
      <span
        className="h-2 w-2 rounded-full bg-emerald-500 inline-block"
        aria-label="done"
      />
    );
  if (status === "error")
    return (
      <span
        className="h-2 w-2 rounded-full bg-destructive inline-block"
        aria-label="error"
      />
    );
  return (
    <span
      className="h-2 w-2 rounded-full bg-muted-foreground/30 inline-block"
      aria-label="idle"
    />
  );
}

function AgentStatusList({
  statuses,
  phase,
}: {
  statuses: Record<TabId, AgentStatus>;
  phase: Phase;
}) {
  if (phase === "idle") return <div className="h-[18px]" aria-hidden />;
  return (
    <div className="border border-border bg-background">
      {TABS.map((t) => {
        const s = statuses[t.id];
        return (
          <div
            key={t.id}
            className="flex items-center justify-between px-3 py-2 border-b border-border last:border-b-0 text-[12px]"
          >
            <span className="text-foreground">{AGENT_LABELS[t.id]}</span>
            <span className="flex items-center gap-2 text-muted-foreground font-mono text-[11px] uppercase tracking-[0.12em]">
              <StatusDot status={s} />
              {s === "running"
                ? "Working"
                : s === "done"
                  ? "Done"
                  : s === "error"
                    ? "Failed"
                    : "Queued"}
            </span>
          </div>
        );
      })}
    </div>
  );
}

function EmptyState() {
  return (
    <div className="border border-dashed border-border bg-surface px-6 py-16 text-center">
      <div className="mx-auto h-12 w-12 border border-border flex items-center justify-center text-foreground font-mono text-sm">
        []
      </div>
      <h3 className="mt-5 text-sm font-medium text-foreground tracking-tight">
        Enter your application concept to spark the AI Systems Architect
      </h3>
      <p className="mt-2 mx-auto max-w-md text-[12px] leading-relaxed text-muted-foreground">
        Architecture diagrams, database schemas, production READMEs, and a
        master AI workflow prompt will appear here once the agents run.
      </p>
    </div>
  );
}

function AgentRunningPanel({ label }: { label: string }) {
  return (
    <div className="border border-border bg-surface px-6 py-12 text-center">
      <div className="flex items-center justify-center gap-2">
        <Spinner />
        <div className="text-[11px] uppercase tracking-[0.22em] text-muted-foreground">
          {label}
        </div>
      </div>
      <h3 className="mt-3 text-sm font-medium text-foreground">
        Generating this section…
      </h3>
      <p className="mt-1 text-[12px] text-muted-foreground">
        You can switch tabs — other agents are running in parallel.
      </p>
    </div>
  );
}

function OutputPanel({
  tab,
  content,
  status,
}: {
  tab: TabId;
  content: string;
  status: AgentStatus;
}) {
  const label = TABS.find((t) => t.id === tab)?.label ?? "";
  return (
    <div className="border border-border bg-surface animate-line-in">
      <div className="flex items-center justify-between px-4 py-2 border-b border-border">
        <div className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground font-mono flex items-center gap-2">
          <StatusDot status={status} />
          {label}
        </div>
        <button
          type="button"
          onClick={() => navigator.clipboard?.writeText(content)}
          className="text-[11px] uppercase tracking-[0.14em] text-muted-foreground hover:text-foreground border border-border px-2.5 py-1 transition-colors"
        >
          Copy
        </button>
      </div>
      <pre className="p-4 md:p-6 text-[12.5px] leading-relaxed font-mono text-foreground whitespace-pre-wrap break-words">
        {content}
      </pre>
    </div>
  );
}
